swizzin/swizzin

scripts/install/rtorrent.sh
scripts/upgrade/rtorrent.sh

Fixes https://github.com/liaralabs/swizzin/issues/127

Switched to xmlrpc advanced to fix the message flooding in rtorrent GUI

---

scripts/install/emby.sh
scripts/upgrade/emby.sh

Updated the url structure of the emby packages

---

scripts/install/nextcloud.sh
scripts/install/sabnzbd.sh

Typo fixes

---

scripts/panel/lang/langSelect-lang_es

Enables spanish language support from swizzin scripts with the quickbox dashboard panel.

Add Spanish language support.

---

scripts/install/filebrowser.sh
scripts/nginx/filebrowser.sh
scripts/remove/filebrowser.sh

Filebrowser 2 installed locally to the main user home directory and configured with the main user credentials as admin.

Filebrowser 2 for swizzin.

---

scripts/install/librespeed.sh
scripts/nginx/librespeed.sh
scripts/remove/librespeed.sh

This commit adds 3 new files for the purpose of including the lightweight [LibreSpeed](https://github.com/librespeed/speedtest/) speed test to Swizzin
LibreSpeed is installed to `/srv/librespeed`
No database or configuration required.

new application: LibreSpeed

---

scripts/install/quota.sh

Suppress apt interactive in quota installer

---

scripts/remove/deluge.sh

Add delugeweb to the lock being removed when removing deluge

---

.github/stale.yml

Just some small things I think would be nice to change

Small suggestions to stalebot

---

README.md

Added codefactor Grade to main page

---

CONTRIBUTING.md

A couple notes on what we might want to try stick to.

Basic Contributing.md file

---

README.md

Every cool project needs some badges
For the discord, a setting needs to be enabled; and it will show the number of people online
https://vimeo.com/364220040

Added Badges for discord and some other stuff

---

.github/ISSUE_TEMPLATE/bug_report.md

Hopefully makes it easier to follow for people.

Cleaned up issue template.

---

.vscode/settings.json
CONTRIBUTING.md
scripts/box
scripts/update/dependencies
scripts/update/dependencies.sh
sources/functions/apt
sources/functions/deluge
sources/functions/rtorrent

Functions to wrap `apt` functions like `update`, `upgrade` and `install` that will have standard behaviour and command line options to streamline the process across all application installations
+ An update script for dependencies will allow us to install global packages which aren't application bound (e.g. `jq`)

Apt functions and global dependency updater

---

scripts/install/vsftpd.sh
scripts/remove/vsftpd.sh

HOTFIX: Remover script for vsftpd

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/config.yml
.github/auto-comment.yml

Added a config file to add more items to the "New Issue" button to channel discussion into the right places

Issue Links

---

sources/functions/apt

Some more fixes for apt overhaul

Last pass over apt update

---

scripts/install/rclone.sh

Added some new settings and fixed some legacy quickbox stuff.

Update rclone.sh gdrive mount settings

---

scripts/remove/vsftpd.sh

HOTFIX vsftpd remover post-apt

---

scripts/install/sonarrv3.sh

Hotfix^2 Sonarr migration path fix

---

README.md

https://swizzin.ltd/getting-started
some cosmetic tweaks.
Where does the donate link go? https://swizzin.ltd/#donate

Update readme link to:

---

README.md

use this shortened URL in all three commands git.io/swizzin

Update readme install commands.

---

setup.sh
sources/functions/pyenv

Fixed the ugly output as seen in Liara's screencaps in #429 , because I didn't target `bionic`

Hotfix pythonvenv and Echos

---

scripts/update/autodl.sh

check for nginx before using this command.

autodl update

---

scripts/box
scripts/install/sonarrv3.sh
setup.sh
sources/functions/ask

Fix `ask` not being sourced globally, fix URL doubling the base

Hotfix box bits

---

scripts/update/mango.sh
sources/functions/utils

Switch to using `find` instead of globbing for more flexibility and predictability. Tested and working.

Hotfix userlist

---

.github/PULL_REQUEST_TEMPLATE/pull_request_template.md

A step towards a more structured process for assessing PRs

PR Template / Checklist

---

scripts/install/autodl.sh

Make autodl download archive once only instead of per every user
Get rid of unnecessary `cd`s which are a disaster recipe

Small autodl install changes

---

.github/workflows/sh-checker.yml
scripts/nginx/sonarrv3.sh
scripts/update/jellyfin.sh
sources/functions/os

Github action to check .sh formatting (and eventually shellcheck too)

Formatting check GitHub action

---

scripts/install/ombi.sh
scripts/nginx/ombi.sh
scripts/remove/ombi.sh
scripts/update/ombi.sh
scripts/upgrade/ombi.sh
sources/functions/ask

- Ombi v3 is EOL
- Radarr v3 not supported in Ombi v3
- _this still keeps isntalling v3 by default_
- Offer upgrade path to v4 through new apt sources via `box upgrade ombi`
- Remove a lot of legacy bloat
- PR link: https://github.com/liaralabs/docs.swizzin.ltd/pull/38
OS & Version: 20.04
- upgraded v3 to v4
- Installed v3 from master
- Checked out to this branch
- Ran `box upgrade ombi`
- Success
- Installed ombi v3 from this branch
- Success
- Same as above but with nginx
- Success
- Fixed the systemd custom service
- Install v3 from master
- run `box update`
- service removed and still running so success

Upgrade path to ombi v4

---

scripts/install/emby.sh
scripts/install/jellyfin.sh

…
- Master failing pipes right now
- Format things
- PR link: 
- PR link: 
OS & Version: 
None

HOTFIX Looks like unformatted commits made it to master because actions don't re-trigger when master moves ahead on its own

---

scripts/install/btsync.sh
scripts/install/couchpotato.sh
scripts/install/jackett.sh
scripts/install/radarr.sh
scripts/install/sonarrv3.sh
scripts/update/permissions.sh

- Incorrectly set permissions after creating `~/.config`
- Don't fuck up `chown` commands
- PR link: 
- PR link: 
OS & Version:

Configperms

---

scripts/upgrade/lounge.sh

- Lounge has no upgrader
- Add an upgrade for lounge
- PR link:  https://github.com/liaralabs/docs.swizzin.ltd/pull/41
- PR link: 
OS & Version: Ubuntu 20.04 
- Install Lounge, then run upgrader.

Lounge upgrader

---

scripts/update/permissions.sh

- `.config` is being worked against when it might not exist
- Check if `config` exists
- PR link: 
- PR link: 
OS & Version:
I haven't and i will eat my shorts if this oneliner isn't a fix

HOTFIX: add extra dir check  on .config updater

---

scripts/install/radarr.sh

it's a one liner
- PR link: 
- PR link: 
OS & Version:

Fixed: Sonarrv3 reference in Radarr installer

---

.gitignore
scripts/box

- It's annoying to maintain symlinks and whatnot just so your git doesn't fuck you with resets
- Add a flag to skip git pulls on updates called `--no-git`
- Add another method to skip the updates by doing `> /etc/swizzin/.dev.lock`
- Impacts the flow of how we contribute (IDE changes, `.github` dir, etc.)
- PR link: 
- PR link: 
OS & Version:

Lockfile updater

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/pull_request_template.md
setup.sh

- `arm64` support is currently "unsupported", and the general tone and process for making these changes needs to be altered
- Add arch specific questions to the PR template
- Add arch specific questions to the Bug report template
- Impacts the flow of how we contribute (IDE changes, `.github` dir, etc.)
- PR link: 
- PR link: 
OS & Version:
This is only GH stuff really
We should eventually discuss how we want to handle testing these things more efficiently. I'm down to set up a raspberry Pi in my home and give SSH keys to it to maintainers.

Preparation for arm64 support

---

.vscode/apt.code-snippets
.vscode/echos.code-snippets
.vscode/general.code-snippets
sources/functions/apt
sources/functions/ask
sources/functions/color_echo
sources/functions/os
sources/functions/pyenv
sources/functions/utils

- N/A
- Add more snippets for missing functions
- Add docs to our functions so they appear like this when Bash-IDE plugin is installed
- Some existing `functions` got changed (e.g. `utils`, `os`, `apt`, `ask`, etc.)
- Notes: 
- Notes: 
- Notes: Just comments and vscode files
- PR link: 
- PR link: 
OS & Version: N/A
N/A
Just specific to vscode and the Bash-IDE plugin

Docs functions+snippets

---

.github/workflows/sh-checker.yml

- Fix failing github actions due to outdated flow
- Change version on flow
- Notes: 
- Notes: 
- Notes: 
- PR link: 
- PR link: 
OS & Version:

HOTFIX: bump sh-checker version to 0.1.10

---

.github/pull_request_template.md
.vscode/settings.json

This PR itself showcases the changes made to the current PR template.
<details>
<summary>Markdown which shows the comments</summary>
(this collapsible is in there by default!)
```md
<details>
</details>
- Issue #nr...
- Bug fix 
- New feature 
- PR link: 
- PR link: 
```
</details>
- Template is slow to fill
- There are no test case examples
- …

Fix PR Checklist & structure

---

scripts/update/radarr.sh

- Broken linke
- Fix link
- Notes: 
- Notes: 
- Notes: 
- PR link: 
- PR link: 
OS & Version:
None
it's one character

fix broken link for radarrv3 updater

---

scripts/upgrade/autodl.sh

- old url isn't working
- it relies on `cd`
- downloads the same exact file as many times as you have users...
- Fix url
- make everything dependant on the directory explicitly instead of using `cd`
- download file once
- add echos
- Some existing `functions` got changed (e.g. `utils`, `os`, `apt`, `ask`, etc.)
- Impacts the flow of how we contribute (IDE changes, `.github` dir, etc.)
- Notes: 
- `arm64` is …

HOTFIX autodl upgrader

---

.vscode/swizdb.code-snippets
sources/functions/quasidb
sources/functions/swizdb
sources/globals.sh

- We don't have a place to store values
- We resorted to using lockfiles, .info files in `root`, and many others and it's now messy
- Start using `/var/lib/swizzin/db` for storing "values" in files named by the keys
- Some existing `functions` got changed (e.g. `utils`, `os`, `apt`, `ask`, etc.)
- Notes: 
- Notes: 
- Notes: nothing but unix baby
- PR link: 
- PR link: 
OS & Version: Ubuntu 20.04 for ARM

Swizzin file-based "quasi-DB"

---

scripts/rtx

I missed an `!` and fucked the thing
- 841b946 doe the opposite of what it should
- Fixed it
- Bug fix 
- PR link: 
- PR link: 

HOTFIX the HOTFIX of rtx

---

.vscode/general.code-snippets

Adds 2 snippets
<details>
</details>
- N/A
- Snippets for checking environment variables
- Snippets for making nginx script install bits
- New feature 
- PR link: 
- PR link: 

SNIPPETS: Added nginx conf, and environment variable checks

---

.gitattributes
scripts/box
scripts/update/sudoers.sh
setup.sh
sources/functions/transmission
sources/functions/users
unattend.example.env

Various issues and potential problems with the unattended installer
- Issue #nr...
- Start using `sudo` group for master instead of sudoers file
- accompanying updater
- Escape all passwords being passed around in `box`
- Allow cracklib skip with `--skip-cracklib`
- Install `uuid-runtime` early as apt functions depend on it
- Fixed `env` file mechanism
- Bug fix 
- PR link: 
- PR link: 
| Focal 		|	✅ 		|		 	|	✅ 		|				|
| Buster		|	✅		|			|			|				|
- env installation
- skipcracklib
- sudo works after install
- passwords change in torrent …

Unattend refinements

---

scripts/install/radarr.sh

- Radarr downloading x86 bins on arm64
- Add multi-arch support
- Remove mono repo installation as sonarr repos handle that themselves
- Notes: Should be uncahnged
- Notes: 
- Notes: 
- PR link: 
- PR link: 
OS & Version: Ubuntu for ARM
- Installed succesfully on Ubuntu for Arm 20.04
Also adds `arm32`, and fails any unknown architectures

ARM support for Radarr

---

scripts/install/sabnzbd.sh
scripts/nginx/rutorrent.sh
scripts/update/10-dependencies.sh
scripts/update/sabnzbd.sh
scripts/upgrade/sabnzbd.sh
setup.sh
sources/functions/rtorrent
sources/functions/utils

- Implements a new python environment management tactic
- Gets sabnzbd ready for v3.2
- Uses userdocs implementation of a template to minimize problems when setting up sabnzbd for the first time
- New update flow
<details>
</details>
```
sed: can't read /home/username/.config/sabnzbd/sabnzbd.ini: No such file or directory
```
- Bug fix 
- PR link: 
- PR link: 

Update sabnzbd and futureproof

---

scripts/nginx/emby.sh

Removes basic auth from Emby, as there is a built in auth system
- Emby asking for auth, breaking apps
- Removed basic auth from nginx config
- Bug fix 
- PR link: 
- PR link: 
None. Minor fix.
ALL
None.
None.

Remove Basic auth from Emby

---

scripts/nginx/sonarrv3.sh

Self explanatory
<details>
</details>
- Issue #nr...
- Bug fix 
- New feature 
- PR link: 
- PR link: 

correct sonarr branch set by nginx

---

scripts/nginx/organizr.sh

Change info message
- Change message from rutorrent to organizr
- Bug fix 
- PR link: 
- PR link: 
Attempt organizr install without nginx
| Focal 		|			|			|	✅		|				|
| Buster		|	✅		|			|			|				|
All.
None.
None.

change rutorrent line to Organizr

---

scripts/install/plex.sh

Plex fails to install when sudo is broken because of invalid characters in usernames
- Edge case
```bash
root@ssgland:~# box install plex
INFO    Installing plex
DOCS    Further reference: https://swizzin.ltd/applications/plex
INFO    Please visit https://www.plex.tv/claim, login, copy your plex claim token to your clipboard and paste it here. This will automatically claim your server! Otherwise, you can leave this blank and to
tunnel to the port instead.
INPUT   Insert your Plex claim token
(e.g. 'claim-...' or blank) >
...     Installing plex keys and sources ...
...     Performing installation of 1 apt packages
(apt-transport-https)
✔   Apt install complete
>>> /etc/sudoers.d/sausage-books: syntax error near line 1 <<<
>>> /etc/sudoers.d/sausage-books: syntax error near line 3 <<< …
```

fix: (plex) remove unnecessary sudo

---

scripts/update/nginx.sh

should have put this change before the nginx reload command or it won't do anything helpful.

fix: make sure command is executed before nginx is reloaded.

---

scripts/update/completion.sh
setup.sh
sources/bash_completion.d/swizzin

Provides bash completion for `box` commands.
Some are statically defined like `panel fix`
`install` `remove` and `upgrade` are dynamic and will return results based on the files that exist relative to those commands.
It is pretty easy to expand or adapt if needed.
- na
- tabbed `box` completion
- New feature 
- PR link: 
- PR link: 

Feature bash completion

---

sources/functions/swizdb

Allows keys to contain slashes so that directories in the database can be made
N/A
- Allow storing keys in directories, e.g. `swizdb set abc/def ghi` would store the `def` key inside of the `abc` directory, and contain `ghi`
- New feature 
- PR link: 
- PR link: 

feat(swizdb): add directory creation for complex keys

---

scripts/update/10-dependencies.sh

Removes `fortune` from dependencies
- remove `fortune` from dependencies
- Bug fix 
- PR link: 
- PR link: 

fix: remove fortune dependency

---

sources/functions/swizdb

Adds a listing feature to the swizdb
N/A
- Add `swizdb list [ key ]`
- New feature 
- PR link: 
- PR link: 

feat(swizdb): add option to list keys, filterable by directory

---

scripts/update/00-checkreqs.sh

Source globals again
- Issue #nr...
- Bug fix 
- New feature 
- PR link: 
- PR link: 

fix(box): re-source globals after git update

---

scripts/box

Fix the help menu
n/A
- Remove panel, fix-panel
- Remove lines between examples for commands
- Bug fix 
- PR link: 
- PR link: 
```
sausage@m1:~$ sudo box help
Usage:  box
box [ install | remove | upgrade ] pkg1 [ pkg2 ... ]
box [ adduser | deluser | chpasswd ] username [ password ]
box [ list | update ]
Note: Only install and remove functions accept package arguments. List
and update must be run without modifiers
install        The install function requires at least one package
name as an argument but will accept multiples
Example: box install quassel syncthing znc
remove         The remove function requires at least one package
name as an argument but will accept multiples
Example: box remove quassel syncthing znc
upgrade        Runs the associated upgrade script.
Example: box upgrade …
```

fix(help): update list and small formatting

---

.github/pull_request_template.md
CONTRIBUTING.md

Explicitly define requirements for a PR to be considered, extra steps on checklist.
- PR link: 
- PR link: 
Not applicable

Update CONTRIBUTING.md and PR template

---

.gitlint

Add file for `gitlint` so that those who opt-in can conform to our commit rules
- non-conform commit message structure
- add `.gitlint` to project root
- opens options for making better changelogs for the future
- PR link: 
- PR link: 
Not applicable

feat: add gitlint rules for conventional commit formatting

---

.vscode/swizdb.code-snippets

Fix snippets for swizdb
- Snippets were formatted wrong
- fixem
- Bug fix 
- PR link: 
- PR link: 
N/A, vscode snippets only

fix(snippets): swizdb

---

.github/workflows/label-conflicts.yml

Labels all PRs that have merge conflicts when a new commit is pushed to master
- N/A
- Use github actions to label the PRs to make them better visible
- New feature 
- PR link: 
- PR link: 
N/A

feat(ci): Label PRs that have conflicts against master

---

README.md

- Issue #nr...
- Bug fix 
- New feature 
- PR link: 
- PR link: 

test: ci trigger

---

sources/functions/users
sources/functions/utils

Fixes user functions not exported
^^
- remove double code
- export properly
- Bug fix 
- PR link: 
- PR link: 
N/A

fix(functions): ensure user functions are globally available, once only

---

scripts/update/radarr.sh

also switch to var based
Grep complains the file is missing if the user customized their installation
- use a var for the config file; check if it exists
- Bug fix 
- N/A Docs have been made OR are not necessary
- PR link: 
- N/A Changes to panel have been made OR are not necessary
- PR link: 

Hotfix: Radarr Updater - Check if Config File exists prior to attempting changes

---

README.md
setup.sh

Just removes xenial from supported codenames at setup.sh
**ALSO CONTAINS COMMIT WHICH IS TAGGED `eol-xenial`**. That is required for #549 
- N/A
- xenial will EOL April 30
- Stop new xenial installs
- PR link: 
- PR link: 

feat: Quickly stop new xenial installs

---

scripts/install/komga.sh
scripts/nginx/komga.sh
scripts/remove/komga.sh
scripts/upgrade/komga.sh
sources/functions/java

!! Depends on #657 
Add Komga to box installs
- Fixes Nothing
- Add Komga to the stack
- New feature / Application
- PR link: liaralabs/docs.swizzin.ltd#72
- PR link: liaralabs/swizzin_dashboard#36
- Tested on AMD64
| Buster		|	✅		|			|			|				|

feat(Komga): Add Komga

---

scripts/install/nzbhydra.sh

unsupport nzbhydra in arm until someone comes along and asks for it
- Issue #nr...
- Bug fix 
- New feature 
- PR link: 
- PR link: 
| Focal 		|			|	❎ 		|	❎ 		|	❎ 			|

fix(nzbhydra): arm support clarification

---

scripts/install/ombi.sh
scripts/update/ombi.sh
scripts/upgrade/ombi.sh

Ombi switched its repo for v4 apt releases. And v3 is EOL so I guess we can't expect support for it anymore.
- Ombi apt sources are unofficial and "develop"
- Switch to recommended and official ombi stable sources
- Bug fix 
- PR link: https://github.com/liaralabs/docs.swizzin.ltd/pull/75
- PR link: 
| Focal 		|			|			|	✅ 		|				|

feat(ombi): Switch sources to new repo, make v4 default

---

scripts/install/emby.sh

Remove mono, add non-amd64 support
- Fixes #483
- Just delete mono lol
- Fix link
- Bug fix 
- PR link: 
- PR link: 
| Focal 		|			|			|		yup	|				|

feat(emby): remove mono, add arm support

---

scripts/box
scripts/update/sudoers.sh

<details>
</details>
- Issue #nr...
- Bug fix 
- New feature 
- PR link: 
- PR link: 

fix: broken sudoers with hyphens

---

scripts/install/radarr.sh
scripts/update/radarr.sh

Minor Echoes
- Echoes
- echose
- Bug fix 
- PR link: 
- PR link: 

fix(radarr): Updater echoes

---

scripts/install/nginx.sh
scripts/install/rutorrent.sh
scripts/nginx/rutorrent.sh
scripts/update/rutorrent.sh
sources/functions/utils

- `cd` failing when `/srv` is not present (so Ubuntu)
- Cloudscraper removed
- rutorrent updater taking long af
- rut installer not failing gracefully
- `mkdir -p /srv`
- Stop using `cd` where possible
- more failure catches
- Check install locks
- Bug fix 
- PR link: 
- PR link: 
| Focal 		|	✅ 		|			|			|				|
- Fresh install on focal

fix(rutorrent): Ensure /srv is created, get rid of cds, remove cloudscraper and python dep

---

scripts/install/nginx.sh
scripts/install/rutorrent.sh
scripts/nginx/rutorrent.sh
scripts/update/rutorrent.sh
sources/functions/swizdb

- Issue #nr...
- Bug fix 
- New feature 
- PR link: 
- PR link: 

refactor: merge master to develop

---

.editorconfig

I was editing the github `yml` files and had to fight editorconfig on every save, so I looked at the `.editorconfig` and configured that yaml should only have 2 spaces for indentation, since all current yml files has this.
- Saving YML in editor supporting editorconfig will reformat the document to incorrect indenation.
- Fixes typos in editorconfig file
* Sets indent_size of yml files to 2 spaces to match existing yml configuration
* Fixes typo in "indent_size"
* Removes unecessary "tab_width" since it defaults to "indent_size" that is now correctly configured ([source](https://editorconfig.org/))
* Stop redefining that indent_style is spaces for `json` too. It's already declared for all files.
- PR link: 
- PR link: 
This is just IDE configurations
|   			| `amd64` …

chore(editorconfig): Fixes to editorconfig

---

scripts/install/jackett.sh

jackett was hardcoded to amd64 binaries
- Switchcase for architectures
- Use right bins
- Bug fix 
- PR link: 
- PR link: 
| Focal 		|			|			|	Yup		|				|
Install with nginx

fix(jackett): Add support for arm architectures

---

.github/pull_request_template.md
CONTRIBUTING.md

The news about `develop` branch needs to make it somewhere, and should be mentioned in PR templates
- PRs being made against master will continute being a thing
- Make this part of the checklist process
- Mention in contribs.md
- PR link: 
- PR link: 
N/A

chore: Mention develop branch in contribs.md and PR template

---

scripts/install/lounge.sh
scripts/update/lounge.sh

Lounge was sitting in `/home` for some reason. yuck
- Lounge not in opt
- move lounge to opt
- Bug fix 
- New feature 
one of those lol
- PR link: 
- PR link: 
- Update from version in master
- Fresh Install with nginx present nginx
- With multiple users present

feat(lounge)!: Move to opt

---

CONTRIBUTING.md
scripts/install/bazarr.sh
scripts/install/nextcloud.sh
scripts/install/nginx.sh
scripts/install/pyload.sh
scripts/install/quassel.sh
scripts/install/sickchill.sh
scripts/install/sickgear.sh
scripts/install/wireguard.sh
scripts/install/znc.sh
scripts/remove/wireguard.sh
scripts/update/bazarr.sh
scripts/update/couchpotato.sh
scripts/update/headphones.sh
scripts/update/nginx.sh
scripts/update/nzbhydra.sh
scripts/update/pyload.sh
scripts/update/sabnzbd.sh
scripts/update/sickchill.sh
scripts/update/sickgear.sh
scripts/update/wireguard.sh
sources/functions/deluge
sources/functions/qbittorrent
sources/functions/rtorrent

Xenial is already deprecated so we can remove it from our codebase
N/A
Remove any xenial logic
- PR link: 
- PR link: 

fix: remove xenial wherever possible

---

scripts/install/transmission.sh
scripts/update/transmission.sh

systems with transmission can have an unresponsive `journalctl` due to the quantity of logs from torrents with errors in a session being spammed into syslog
- `journalctl`/`systemctl` being slow on systems with transmission
- Move logs to a dedicated file
- Bug fix 
- PR link: 
- PR link: 
| Focal 		|			|			|			|	🛠			|
- Test install from scratch (MU/single does not matter)
- Test update on existing install (MU/Single does not matter)

fix(transmission): Move logs out of syslog

---

scripts/install/pyload.sh
sources/functions/pyenv

`pip` on focal is from python3, there isn't a `pip3`. Therefore the pip installation for `python2` gets skipped, and that one also contains installing `virtualenv` for python2
- Fixes #677 
- virtualenv not installing for python 2 on focal
- Ensure that when `pip` is referred to in the function affected, it is explicitly the python2 one and not the python3 one.
- Bug fix 
- PR link: 
- PR link: 
| Focal 		|			|			|	yup		|				|

fix: virtualenv installation on focal

---

.vscode/extensions.json
.vscode/settings.json
commitlint.config.js

- Issue #nr...
- Bug fix 
- New feature 
- PR link: 
- PR link: 

feat(ide): conventional commit support

---

README.md

poor grammar and spelling
...see diff
- git
N/A - Git

docs(readme): spelling/grammar

---

scripts/remove/ombi.sh

Ombi configs don't purge right and it's not clear if it's intended or not
- #570
- Trying to reinstall ombi after borking an install will not really do much to reset it
- Offer purge prompt
- Purge via apt if asked to do so
- Bug fix 
- New feature 
- PR link: 
- PR link: 
| Focal 		|	✅		|			|	✅		|				|
- Removal removes configs
- Install after purged removal starts with a clean setup

feat(ombi): offer config purging

---

scripts/nginx/lounge.sh

Old paths in the nginx installer for lounge that I missed somehow.
Quick dirty fix from the web view
- Bug fix 
- PR link: 
- PR link: 

fix(lounge): Outdated config path in nginx installer

---

scripts/upgrade/curl.sh

- Issue #nr...
- Bug fix 
- New feature 
- PR link: 
- PR link: 

hotfix(curl): update to new upstream and build reqs

---

scripts/remove/netdata.sh

Use actual uninstaller script from netdata instead of removing things one by one
- Closes #593
- fix: apply suggestion from #593
- fix: clean up double responsabilities, catch possible failures
- Bug fix 
- New feature 
- PR link: 
- PR link: 
| Focal 		|			|			|		yup	|				|

fix(netdata): use upstream remover

---

sources/functions/qbittorrent

- Issue #nr...
- Bug fix 
- New feature 
- PR link: 
- PR link: 

hotfix(qbittorrent): don't install recommends with qt toolchain

---

scripts/update/btsync.sh

See changelog
Bad btsync updater
- Fix issue
- Bug fix 
- PR link: 
- PR link: 

fix(btsync): bad service name in updater

---

scripts/install/lounge.sh
scripts/remove/lounge.sh
scripts/update/lounge.sh
sources/functions/npm

- fix: lounge remover
- fix: restructured lounge updater
- fix: catch some possible failures
- fix: add failure catching to npm function
- broken lounge updater and remover
- change the logic, update paths
- Bug fix 
- PR link: 
- PR link: 
| Focal 		|			|			|	yup		|				|

fix(lounge): forgotten paths and exceptions

---

scripts/box

stop letting `box` change passwords for users that don't exist
`box chpasswd` did not check if a user actually existed or not before attempting to make it
- `id $user` and kill if fail
- Bug fix 
- PR link: 
- PR link: 
| Focal 		|			|			|	Yup		|				|

fix: kill chpasswd if user does not exist

---

scripts/update/10-dependencies.sh

`unzip` is being taken for granted, so let's make that a thing
n/a
- add `unzip` to deps
- Bug fix 
- New feature 
- PR link: 
- PR link: 
| Focal 		|			|			|	yup		|				|

fix: add unzip to dependencies

---

scripts/install/bazarr.sh
scripts/nginx/bazarr.sh
scripts/remove/bazarr.sh
scripts/update/10-dependencies.sh
scripts/update/bazarr.sh

Git clone is no longer supported as an install method for bazarr
- Fixes #722
- style: separation into functions
- fix: #722
- fix: update nginx config
- fix: echos, logs, small logic, service
- Bug fix 
- PR link: 
- PR link: 
| Focal 		|	Yup		|			|	Yup		|				|

fix(bazarr): change deployment method

---

scripts/upgrade/autobrr.sh
sources/functions/autobrr

Little forgotten variable in upgrader
- Bug fix 
- PR link: 
- PR link: 
| Focal 		|			|			|		yup	|				|

fix(autobrr): loop through users on upgrade, echo

---

scripts/install/bazarr.sh
scripts/install/sonarr.sh
scripts/nginx/sonarr.sh

Clean up the new config directory change from `.config/sonarr` to `.config/Sonarr`

fix(sonarr): config dir case

---

.gitignore

Just adding `.idea/**` to the .gitignore so that I don't have to do it on every PR until an actual .idea PR is made.
Having to ignore it in each of my PRs.
Self explanatory
- PR link: 
- PR link: 
Not necessary.
Not necessary.

fix: ignore JetBrains .idea folder

---

scripts/install/filebrowser.sh
scripts/upgrade/filebrowser.sh

Enables multi-arch installs, cleans up legacy formatting
Fixes #758
- fix: arch detection
- fix: splitting download logic
- fix: split into functions
- fix: formatting
- fix: function reuse, tigher permissions
- Bug fix 
- PR link: 
- PR link: 
| Focal 		|			|			|	yeah		|				|

fix(filebrowser): arm-compatibility & code style

---

scripts/box

- Not enough brr
- Super sekret easter egg
- Install `mpv` with no recs (x11 trying to sneak in)  for easter egg backend

feat(autobrr): super important autobrr business

---

scripts/install/calibreweb.sh
scripts/update/calibreweb.sh

Updates calibre web to fix future issues
- Fixes #735 
- Fixes #788 
- Add updater file to check venv deps and update if required.
- Remove `-f` flag from install and update existing installs
- Bug fix

 fix(calibreweb): update venv reqs and remove -f flag 

---

sources/functions/npm

- Bump node version to 16 LTS
- New feature 
- PR link: 
- PR link: 

Bump node version to 16 LTS

---

sources/functions/deluge

The git branch in the script does not match the real tags in deluge git repo.
- Issue #806 
Create a new variable to store the gitbranch
- Bug fix 
- PR link: 
- PR link: 
- Fresh VM on GCP (amd)
- Fresh Docker Ubuntu (arm)
| Focal 		|	✅		|			|	✅		|				|
- Run formatters 
- Check that variable naming scheme is proper

WIP: Fix Deluge 1.3 failing to install

---

scripts/install/nginx.sh
scripts/rtx
scripts/update/nginx.sh

share/media broke because of autoloads

fix(rutorrent): pin versions of filemanager-share and media to match fm

---

scripts/install/jackett.sh

- Change install method for jackett to use the new `github_latest_version` function. 
- Hardcoded part of the link to clear up the Linux rather than macOS designation.
- Bug fix 
- PR link: 
- PR link: 
| Focal 		|			|			|		✅	|				|

fix(jackett): correct arch on arm64

---

sources/functions/qbittorrent

- change from `-b $QT_VERSION` to `-b "v${QT_VERSION}"`
- Bug fix 
- PR link: 
- PR link: 

fix: qt git tagging changed.

---

scripts/nginx/bazarr.sh

- Swap the sed command for baseurl in nginx/bazarr.sh.
- Bug fix 
- PR link: 
- PR link: 

fix: Bazarr config issue

---

scripts/install/btsync.sh
scripts/install/jellyfin.sh
scripts/install/nginx.sh
scripts/install/ombi.sh
scripts/install/plex.sh
scripts/install/syncthing.sh
scripts/install/webmin.sh
scripts/install/x2go.sh
scripts/update/jellyfin.sh
scripts/update/ombi.sh
scripts/upgrade/ombi.sh
setup.sh
sources/functions/deluge
sources/functions/java
sources/functions/mono
sources/functions/qbittorrent
sources/functions/rtorrent

I'm pretty sure most of this stuff works.
Pushing to dev for bigger audience

Jammy Support

---

scripts/update/mylar.sh
scripts/update/organizr.sh
scripts/update/rutorrent.sh
scripts/update/tautulli.sh
scripts/upgrade/panel.sh

https://github.blog/2022-04-12-git-security-vulnerability-announced/
Breaks git pull requests since we run everything as root. Simple solution: run all git pull commands prefaced with `sudo -u <user that owns the dir>`
No more error

fix(git): pull repo updates as user owning repo (Fixes #858)

---

.github/ISSUE_TEMPLATE/BUG_REPORT.yml
.github/pull_request_template.md
scripts/box

- Un-tracked issue: allows box update on jammy
- flick switch
- Bug fix 
- PR link: 
- PR link: 

fix: enable jammy support

---

scripts/update/nginx.sh

changes to the mechanism found here in the updater: https://github.com/swizzin/swizzin/blob/659b1c51fbcf277c7349ce7caaf812c85f01d382/scripts/install/nginx.sh#L37-L54
- Check for php-geoip dependant on os
- Bug fix 
- PR link: 
- PR link: 

fix: geoip / mcrypt nginx updater for jammy

---

.github/FUNDING.yml

GHS for Brett
- Add Brett to funding.yml
- Contribution flow

Add Brett to finding

---

scripts/install/emby.sh
scripts/upgrade/emby.sh

Emby upgrade script doesn't have any handling for arm installs
- Discord report
Also replaced the version curling with the newer latest release function for ease of use and "best practices"

fix(emby): upgrader qol and arm fixes

---

sources/functions/qbittorrent

- Discord report
- match differently
- Bug fix 
- PR link: 
- PR link: 

fix: qbittorrent version resolution

---

scripts/install/wireguard.sh

Fixes: https://github.com/swizzin/swizzin/issues/851

fix(wireguard): iptables dependency

---

scripts/install/lounge.sh
scripts/remove/lounge.sh
scripts/update/lounge.sh
scripts/upgrade/lounge.sh
sources/functions/npm

- Un-tracked issue... https://github.com/thelounge/thelounge/issues/4532
- https://github.com/swizzin/swizzin/issues/856
- swap to thelounge
- add yarn installation to the npm source file
- Bug fix 
- PR link: 
- PR link: 

fix: swap to yarn for thelounge instances

---

scripts/upgrade/lounge.sh

- Discord Report
- ensure npm functions are sourced
- Bug fix 
- PR link: 
- PR link: 

fix: ensure npm is sourced for yarn install

---

README.md

It seems the FeatHub domain expired and was auctioned off. I saw this at http://feathub.com today. It was sold about an hour ago to someone.
Maybe nothing will come of it and the buyer is the current owner -- or it could become an ad farm.
- FeatHub is down and domain sold at auction.
- Removed it from the Readme.
- Readme only.
- PR link: 
- PR link: 
- [x Shellcheck isn't screaming [(See more)](https://github.com/swizzin/swizzin/blob/master/CONTRIBUTING.md#editor-plugins-and-tooling)
| Raspbian  	| …

Remove FeatHub from readme

---

scripts/nginx/transmission.sh
scripts/update/nginx.sh

Add fancy index line another torrent clients.
- New feature
- PR link: https://github.com/swizzin/swizzin_dashboard/pull/53
- [] Testing was done
- [] Tests created or no new tests necessary
- [] Tests executed
I was tested only on a server with Ubuntu 20.04
| Focal 		|		✅	|			|			|				|

Add nginx fancy index config for transmission.

---

scripts/install/jellyfin.sh
scripts/nginx/jellyfin.sh

Further fixes for new network.xml expectations

fix(jellyfin): create network.xml with proper values

---

sources/functions/fpm

bionic: fix fpm install

---

scripts/install/calibre.sh
scripts/upgrade/calibre.sh

- Closes https://github.com/swizzin/swizzin/issues/890
- Discord Report
- ensure `libopengl0` is installed.
- Bug fix 
- PR link: 
- PR link: 
| Focal 		|	✅		|			|			|				|

fix: ensure `libOpenGL.so.0` is installed.

---

scripts/install/quassel.sh

still needs more work.
- Install using apt source in bullseye
- Need to fix: dead link in else.
- Bug fix 
- PR link: 
- PR link: 

Fix: Bullseye Quassel Installs

---

sources/functions/deluge

- pin Automat version
- Bug fix 
- PR link: 
- PR link: 
| Bullseye		|		✅	|			|			|				|

fix: Deluge pin Automat verson

---

sources/functions/qbittorrent

- Adds support for qBittorrent 4.5 / LT 1.2 builds using same deps as 4.4.x
- PR link: 
- PR link: 
| Focal 		|			|			|	✅		|				|

feat: qBittorrent 4.5.x Support

---

sources/functions/npm

- Track current LTS version of node
- Bug fix 
- PR link: 
- PR link: 
| Bullseye		|		✅	|			|			|				|
Upgraded lounge, succeeded.

fix(node): bump version to 18.x

---

README.md
scripts/box
setup.sh

Initial removal of support for stretch and bionic.
eol- branches can be tagged from this commit and bionic/stretch code can start to be removed after this.

meta: EOL stretch and bionic

---

README.md

Replace out of date feathub link in first sentence

Meta: update readme

---

scripts/install/lounge.sh

- Issue #970
- Remove the depreciated `npm config set` method
- Bug fix 
- PR link: 
- PR link: 
| Raspbian  	|			|			|	✅		|				|

hotfix: remove problematic `npm config set`

---

scripts/install/nzbhydra.sh

- Bug fix 
- PR link: 
- PR link: 

fix: nzbhydra broken var

---

sources/functions/mylar

- Un-tracked issue. 
- Bug fix 
- PR link: 
- PR link: 

hotfix: mylar urllib3 patch

---

sources/functions/qbittorrent

Fixes missing deps in bookworm compile.
- Add apt install for the same deps required for jammy/bullseye to bookworm.
- Bug fix 
- PR link: 
- PR link: 

fix: missing deps for qbit compile

---

sources/functions/deluge

- Adds optimizations to deluge (tested on 2.1/bookworm)
- PR link: 
- PR link: 
| Bookworm		|	✅		|			|			|				|

maintenance: deluge compile optimizations

---

scripts/install/mango.sh

- Issue #1017 
- Block Mango install on arm
- Bug fix 
- PR link: 
- PR link: 
It'll be fine

Stop installing mango on arm

---

.pre-commit-config.yaml

Adds quick pre-commit checks for shfmt and shellcheck
- Add precommit hooks
- PR link: 
- PR link: 
N/A

Add pre-commit definitions

---

sources/functions/curl

Fix curl regression with GCC 12 on Jammy

---

sources/functions/qbittorrent

qbit: fix qt6 repo deps

---

sources/functions/qbittorrent

qbit: fix focal dependencies

---

scripts/update/nginx.sh

- `php-mcrypt` is not supported on any swizzin platforms. `php-geoip` is only supported on three swizzin platforms.
- Use tertiary syntax for `php-geoip`. Task can be accomplished in 1 readable line instead of 19 lines of code.
- Remove package "missing" check. The `apt_install` wrapper will do this for us. This code is redundant.
- Fix a bug causing incorrect purging of `php7.0-fpm`.
- Remove redundant setting of `phpversion` variable.
- Comment code for better readability.

Nginx: Maintain update code

---

setup.sh

Helps prevent the scenario in which #1050 occurs

setup: remove user from url, add info about 403 error

---

sources/functions/npm

Removes nodesource script due to depreciation notice.
- #1089
- PR link: 
- PR link: 

npm: depreciate nodesource script

---

sources/functions/qbittorrent

Added lines for version 4.6
Added lines to support the new qBittorrent version 4.6
- PR link: 
- PR link: 
-Update from existing 4.5.5 to 4.6 with additional software tests, coudn't see any error or other problems.
-fresh install of version 4.6 should be tested.
| Bullseye		|		✅	|			|			|				|

Update to support qBittorrent version 4.6

---

sources/functions/rutorrent

Makes ruTorrent great again with the Country Flags feature!

ruTorrent: Add country flags back!

---

scripts/install/nginx.sh
scripts/update/nginx.sh

Disable emitting nginx version for HTTP protocol
Reference:
https://nginx.org/en/docs/http/ngx_http_core_module.html#server_tokens
https://www.gnu.org/software/sed/manual/sed.html

Disable emitting nginx version

---

scripts/install/netdata.sh
scripts/remove/netdata.sh

netdata: update kickstart URL

---

scripts/install/nzbhydra.sh
scripts/upgrade/nzbhydra.sh

Fixes #1073 
Installing for me currently with Debian 12

Nzbhydra fixes

---

sources/functions/npm

- npm install failures for lounge. 
- bump node to version 20
- PR link: 
- PR link: 

maintenance: bump node to 20.x LTS

---

scripts/install/nginx.sh
scripts/update/nginx.sh

- Issue #nr...
- New feature           
- Breaking change       
- Project structure     
- Contribution flow     
- PR link: 
- PR link: 

fix: svn-depreciation

---

scripts/install/nginx.sh
scripts/update/nginx.sh

- Issue #nr...
- New feature           
- Breaking change       
- Project structure     
- Contribution flow     
- PR link: 
- PR link: 

nginx: fix fancyindex installation

---

sources/functions/rutorrent

- Cleanup unused code
- Print proper error messages
- Replace svn co with git clone

ruTorrent: Fix Installation Issues

---

sources/functions/qbittorrent

Hotfix.
- PR link: 
- PR link: 

fix: add `qt6-base-private-dev` dep

---

README.md
setup.sh

All the major/most common stuff seems to work. The following cases were tested:
- Qbittorrent 4.6.4
- rTorrent 0.9.8 + ruTorrent
- Deluge 2.1
- Sonarr
- Radarr
- Prowlarr
Will likely merge as-is and let bug reports filter in for remaining broken items

Noble support

---

sources/functions/deluge

- Issue #1171 
- Use Jamfile to get VERSION
- PR link: 
- PR link: 
| Bullseye		|	✅	|			|			|				|

deluge: Use Jamfile to get VERSION (#1171)

---

scripts/update/10-dependencies.sh

Adds the rsyslog package to mitigate an issue with fail2ban installs not starting on Debian 12 installs
- Issue #nr...
- PR link: 
- PR link: 

security: rsyslog for fail2ban

---

scripts/nginx/sonarr.sh
scripts/update/sonarr.sh

I've extended the Nginx setting `proxy_read_timeout` for `sonarr/api` to prevent timeouts during interactive searches in Sonarr. This adjustment is necessary because Sonarr sometimes performs searches on a per-episode basis, which can take a long time and result in Nginx timing out.
- Extended proxy_read_timeout for `sonarr/api`
- PR link: 
- PR link: 
Ran a interactive search in Sonarr on a series that takes a long time and after 60 seconds i get the result "Unable to load results for this episode search. Try again later". 
Ran `box update sonarr` after i checked out my branch(made sure output showed `Upgrading nginx config for Sonarr`). Tested the interactive search again and it completed after a long time now.
Ran `box update sonarr` again and confirmed that …

fix: long interactive searches with nginx

---

scripts/box

Remove Buster AS LTS is now EOL
- Remove Buster AS LTS is now EOL
- 
- Remove Buster AS LTS is now EOL
- Breaking change       
- [ x] Branch was made off the `develop` branch and the PR is targetting the `develop` branch
- [ x] Docs have been made OR are not necessary
- PR link: 
- [x ] Changes to panel have been made OR are not necessary
- PR link: 
- [ x] Code conforms to project structure [(See more)](https://swizzin.ltd/dev/structure)
- [x ] Prints to terminal are handled [(See more)](https://github.com/swizzin/swizzin/blob/master/CONTRIBUTING.md#printing-into-the-terminal)
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x ] Testing was done
- [ x] Tests created or no new tests necessary
- [ x] Tests executed
|   			| `amd64` 	| `armhf` 	| `arm64` 	| …

Remove Buster AS LTS is now EOL

---

scripts/nginx/sabnzbd.sh

Fixes baseurl
https://github.com/swizzin/swizzin/issues/1216
.
- PR link: 
- PR link: 

fix(sabnzbd): Base url fix

---

sources/functions/qbittorrent

This PR adds support for the qBittorrent 5.1.x versions.
Boost version has **not** been bumped.
- Added qBittorrent 5.1.x versions to the installer and bumped `libtorrent_minimum_version` to `1.2.20`
- New feature: qBittorrent 5.1.x support    
- Changes in `box install qbittorrent` / `sources/functions/qbittorrent`
- PR link: *not necessary*
- PR link:  *not necessary*
Tested installation of qBittorrent v5.1.0 on a fresh minimal installation VM of Debian 12.10.0 with a single user.
Panel and nginx have been installed at setup. qBittorrent has been installed with `box install` afterwards.
Ran `box test` and `box test qbittorrent` which both resulted in "All tests completed succesfully."
If additional testing is required please let me know.
qBittorrent 5.1.x with boost 1.86.0 has also been …

feat(qbittorrent): add support for 5.1.x

---

sources/functions/deluge

Deluge not compiling.
- Makes changes to Deluge compile to repair functionality of Deluge 2.1 (moving off master and over to git tags) and also adds support for Deluge 2.2. As Deluge team seems to be moving towards committing more directly to master, tags were evaluated as the best way forward.
- Project structure     
- PR link: 
- PR link: 
| Bookworm      |        ✅   |           |           |               |

fix(deluge): Deluge 2.2 Support

---

sources/functions/utils

Changes RAM check requirements to 4GB as compiles on less were breaking.
OOM on compile.
4GB instead of 2GB for swapon.
- PR link: 
- PR link: 
| Bookworm      |           |    ✅       |           |               |

fix(utils): Increase RAM requirements for compiles

---

scripts/install/nginx.sh
scripts/update/nginx.sh

Fixes a conflict between the server {} directive and proxy.conf, where server dictates max_body_size is 40M, and proxy.conf snippet sets it to 10M inside the location.
- Un-tracked issue.
- Fixes a conflict between the server {} directive and proxy.conf, where server dictates max_body_size is 40M, and proxy.conf snippet sets it to 10M inside the location.
- 
- PR link: 
- PR link: 

fix: sync `client_body_buffer_size` with main config
