swizzin/swizzin

scripts/deluge.UpdateTracker.py
scripts/install/deluge.sh
scripts/remove/deluge.sh
scripts/upgrade/deluge.sh

This PR adds the [update-tracker](https://github.com/s0undt3ch/Deluge/blob/master/deluge/ui/console/commands/update-tracker.py) command to Deluge regardless of Deluge installation type (repo, stable, or dev). The `update-tracker` comes in handy with problematic trackers to programmatically force-reannounces and avoid using pause/resume.
Furthremore, deluge-console was missing when installing Deluge from repo. This PR adds it. It also removes deluge-console if it was installed from repo.
(I am using nope@nope.com as e-mail for git, which I guess is the same for the poor danburg user.)

Adds the update-tracker command to Deluge console (repo, stable, and dev)

---

scripts/install/deluge.sh

Recently,  libtorrent attempts to use the folder `/usr/local/include` when creating the package with checkinstall. The installation fails with 
```make[2]: Nothing to be done for 'install-exec-am'.
/bin/mkdir -p '/usr/local/include/libtorrent'
/bin/mkdir: cannot create directory ‘/usr/local/include’: No such file or directory
Makefile:587: recipe for target 'install-nobase_includeHEADERS' failed
make[2]: *** [install-nobase_includeHEADERS] Error 1
make[2]: Leaving directory '/home/kaput/tmp/libtorrent/include/libtorrent'
Makefile:706: recipe for target 'install-am' failed
make[1]: *** [install-am] Error 2
make[1]: Leaving directory '/home/kaput/tmp/libtorrent/include/libtorrent'
Makefile:621: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1
**** …
```

Fixes failure to create .deb for libtorrent

---

scripts/install/rclone.sh

Use one-liner from https://rclone.org/downloads/; use https now instead of http link before; do NOT make system service, unless rclone install proceeds without issue.

Massively simplify rclone installation

---

scripts/install/sabnzbd.sh
scripts/remove/ombi.sh

Fixes are typo in the sabnzbd installer and also ensures that ombi is completely removed when running box remove ombi

Random fixes

---

scripts/install/deluge.sh

Deluge install is missing a . which causes libtorrent to be undefined if it was already installed.

Fix libtorrent lock file address 

---

scripts/install/jellyfin.sh
scripts/nginx/jellyfin.sh
scripts/remove/jellyfin.sh
scripts/upgrade/jellyfin.sh

https://jellyfin.org/
This commit adds 4 new files for the purpose of including the jellyfin media server to swizzin
Jellyfin installed to `/opt/jellyfin`
Ffmpeg using latest stable static build from https://johnvansickle.com/ffmpeg/
Ffmepg installed to `/opt/ffmpeg`
Database and configuration files are in the default local user directory `/home/${username}/.config` directory.
Permissions assumed and set as the swizzin default local user `${username}`.
install/nginx/remove/upgrade scripts

new application: Jellyfin

---

scripts/install/letsencrypt.sh

The current regex used to prohibit TLDs that Cloudflare doesn't support is wrong, it should look for Anything.ProhibitedTLD but instead it looks for AnythingProhibitedTLDAnything. 
For example, the domain "the-abbreviation-for-the-state-of-georgia-is-ga.com" will be rejected because it contains some characters, followed by "ga" (a prohibited TLD), followed by some characters.
This change ensures that the regex only matches against a literal period, then a prohibited TLD, then the end of the hostname.

Fix letsencrypt failure if Cloudflare domain is on allowed TLD but has substring of a prohibited TLD

---

sources/functions/rtorrent

Should resolve the following issues found in end-user's log
```
user@host:~$ sudo cat /root/logs/swizzin.log
Reading package lists...
Building dependency tree...
Reading state information...
The following packages will be REMOVED:
rtorrent
The following held packages will be changed:
rtorrent
0 upgraded, 0 newly installed, 1 to remove and 0 not upgraded.
E: Held packages were changed and -y was used without --allow-change-held-packages.
```

Make sure held packages are removed

---

setup.sh

Just to make sure users know what "master" means and that they will change their password if they are re-using an existing account.
Notice `Swizzin "master"`
Notice `new password for $user`

Clarify master user dialogues in setup, adjust whiptail sizes

---

sources/functions/transmission

I noticed Focal was missing from the distributions that can get the PPA and with transmission 3.0 it makes sense to add the PPA to focal too. Might as well do this for all Ubuntu releases.

Hotfix: Ensure PPA is available for all Ubuntu releases

---

scripts/install/znc.sh

No ZNC ppa for focal so we fall back to 1.7.5 which is in apt.
The le hook thing needs nginx to begin with so check for at least that, otherwise it will always run with or without letsencrypt

HOTFIX znc focal ppa

---

scripts/update/mango.sh

The file broke the output of the `_get_user_list` function. We really need to restructure that whole mechanism

HOTFIX: remove dumb mango file

---

scripts/update/jellyfin.sh

Make sure user's libraries are fully migrated by editing paths in the library.db. These changes are determined by the existence of library folders in the data folder.
Please see this commit for specific changes to avoid getting lost in the formatting change.
https://github.com/swizzin/swizzin/commit/76fcb0ae9a30cfdb2fd339938113972f240b4905

jellyfin migration fix:

---

sources/functions/qbittorrent

The qBittorrent script doesn't support specific qBittorrent versioning and doesn't pull the latest version:
```
curl -s https://github.com/qbittorrent/qBittorrent/releases | grep .tar.gz | grep -oP '\d.\d?.?\d'
4.3.0
4.3.0
4.2.5
4.2.4
4.2.3
4.2.2
4.2.1
4.2.0
4.1.9
4.1.9
```
```
curl -s https://github.com/qbittorrent/qBittorrent/releases | grep .tar.gz | grep -oP '\d.\d?.?\d?.?\d'
4.3.0.1
4.3.0
4.2.5
4.2.4
4.2.3
4.2.2
4.2.1
4.2.0
4.1.9.1
4.1.9
```

Fix qbittorrent regex to include minor bugfix versions

---

scripts/nginx/jellyfin.sh

- N/A
- use `proxy_set_header Host \$proxy_host;` instead of `proxy_set_header Host \$host;`
- ...
- PR link: 
OS & Version: N/A
Panic averted!
- I ran this on a vm using a local ip. it works

fix: jellyfin reverse proxy with internal ip addresses.

---

scripts/box
setup.sh
sources/globals.sh

- Keeping `box` and `setup.sh` in sync with sources
- Debugging or testing individual files right now is a pain because of the imports that are all over
- Move all imports to one file
- Properly detail how these imports need to work
- Make `setup.sh` and `box` point to this file as soon as it's available
- PR link: 
OS & Version: Ubuntu 20.02
- Ran `box` commands that included an `ask` and `apt_install`, `echo`es are given to run too.
- Made a full run of `setup.sh` with no problem
- Sourced the `globals.sh` file and ran individual scripts directly

Moving global sources to one file

---

scripts/update/ombi.sh

Ombi service was enabled before `box update` changed the service file back to the repo version, but is disabled after the update
Check if `/etc/systemd/system/multi-user.target.wants/ombi.service` is a broken symlink and re-enable ombi if it is.
- PR link: 
- PR link: 
OS & Version: Debian 10
The `enable` command removed the broken symlink and added a link to the correct service file in my testing
Only tested on Debian 10

Fix ombi service reading as disabled after service update

---

.editorconfig

- Formatting in vstudio still switching to tabs because of `./editorconfig`
- Fix `./editorconfig`
- Impacts the flow of how we contribute
- PR link: 
- PR link: 
OS & Version:

Ensure .editorconfig is set to spaces

---

scripts/install/emby.sh
scripts/install/jellyfin.sh

- JF and Emby can be installed side by side but their ports are clashing and they're a fork of one another anyway
- One of dan's customers got this
- Disable the service of the other program during install, or quit the installer.
- PR link: 
OS & Version: Ubuntu 20.04
- None at all just yet. This works for the Medusa, Sickrage and Sickchill combo so I would assume it works here too.

Reapply sicko-mode logic to JF and Emby seeing as they're forks of each other

---

scripts/install/panel.sh
scripts/nginx/panel.sh
scripts/update/panel.sh
scripts/upgrade/panel.sh

- Panel now requires python3.6+
- Update scripts to detect whether or not the venv needs an upgraded python version
- Align swizzin_dashboard venv with our standard venv folder (`/opt/.venv`)
- Use `scripts/install/panel.sh` to pull people away from old dashboard onto the new one so we don't have to constantly maintain that section of the script
- QoL/Best Practices
OS & Version: Debian 10
- Fresh install on Debian 10
- `box update` on Debian 10

Update python minimum version of the panel to 3.6

---

scripts/update/plex.sh
scripts/upgrade/plex.sh

- Issue with not being able to easily re-run the plex upgrader
- Remove lockfile
- Directly call upgrader script after it has been installed when requested
- PR link: https://github.com/liaralabs/docs.swizzin.ltd/commit/b76cc18ab8ac979f545cfee6f281ad57301c50ac
- PR link: 
OS & Version:

Hotfix plex upgrade lockfile boogaloo

---

scripts/update/00-venv.sh

- `-bash: /opt/.venv/swizzin/bin/pip: /opt/swizzin/venv/bin/python3: bad interpreter: No such file or directory`
- after moving virtual environments, pip will not function because the env is still pointing to the wrong location
- `sed` the correct path into venvs if a fix is needed
- PR link: 
- PR link: 
OS & Version:
grep and sed commands tested on Debian 10
- Beyond sed and grep nothing at the moment

Fix venv paths that were mistakenly not updated during virtualenv migrations

---

scripts/install/x2go.sh

- X2Go installer contains midori, which is bloat and can break installs when it's not available
- Remove midori
- PR link: 
- PR link: 
OS & Version:
As if this won't work

remove midori from x2go installer

---

scripts/rtx

- `rtx` can run even if rutorrent is not installed
- Add a lockfile check and `exit 1` if rutorrent is missing
- Notes: 
- Notes: 
- Notes: Just a lockfile check that
- PR link: 
- PR link: 
OS & Version:
None, should just work

HOTFIX don't run rtx when no rutorrent installed

---

scripts/nginx/mango.sh
scripts/update/mango.sh

N/A
-  Proxy WebSocket in Mango Nginx config
- Notes: 
- Notes: 
- Notes: 
- PR link: 
- PR link: 
OS & Version: Ubuntu 20.04, amd64
Since v0.17.0, Mango uses WebSocket on the download manager page. This PR updates the Nginx config so Nginx would proxy the WS requests to Mango.

IMPROVE: Nginx WebSocket support for Mango

---

scripts/install/mango.sh

- Mango installer on `arm` wrongly succeeds
- Cancel builds on `arm` explicitly
- Handle failure of other architectures
- Notes: 
- Notes: Crystal can't build statically linked arm bins, following mid-stream (is that a word?) https://github.com/hkalexling/Mango/issues/131
- Notes: 
- PR link: 
- PR link: 
OS & Version: Focal for `arm`
- Successfully fails to install on `arm64`

Mango on Arm (fail until issues upstream of upstream are rresolved )

---

scripts/install/sonarrv3.sh

This will test for the api to load and return a valid http response every 3 seconds before moving on.
If there is no response after the 30 seconds the command will fail and exit the script.
I've hardcoded the port because it takes at least 5 seconds for the config to be generated and populated and I feel the only way to sensibly resolve that is to generate a config and not test/look for it as it's unpredictable.

improve wait for sonarr v3 to load

---

scripts/box
scripts/update/00-checkreqs.sh

Globals needs to be sourced after git pull and before running the update scripts in a subshell.
- swizdb changes error on update

fix: make sure globals is resourced before updating apps.

---

scripts/update/mono.sh

- Issue #nr...
- Bug fix 
- New feature 
- PR link: 
- PR link: 

fix(mono): quiet the apt-key command

---

sources/bash_completion

Fixes the completion not tabbing through the apps/upgrade list after the first result.
It now tabs as many times as needed
`box install TAB app TAB app TAB app`
and
`box remove TAB app TAB app TAB app`
Also removed `cat` command expansion as it turns out I can pass the file directly.
committed to `mapfile` instead of `readarray`
change made with help in `#bash`
- Un-tracked issue: bash completion not tabbing through apps list for multiple selections
- minor changes to the completion file.
- Bug fix
- PR link: 
- PR link: 
Debian Stable
| Buster		|	✅		|			|			|				|
| Raspbian  	|	⚫️		| …

fix bash_completion

---

sources/functions/swizdb

- fix(swizdb): check if key is file or link
- fix(swizdb): return code of first command in path
Return codes from swizdbget could give false positives
- those false psotives
- Check keys more strictly
- Return error code of `cat` without that of `tee`
- Bug fix 
- PR link: 
- PR link: 
(and when I disable the path check first, the pipestatus still catches that)

fix(swizdb): handle bad keys in gets better

---

sources/functions/swizdb

- `swizdb` path changing behaviour since the switch from `-e`
- Add exit code 2 to `swizdb path` when a directory is encountered as key
- BUT still echo the full path of the dir
- rest of the functions continue to work as intended
- Add trailing slash to the return of `swizdb path` when a directory is encountered.
- Bug fix 
- PR link: 
- PR link: 
| Focal 		|			|			|	✅ 		|				|

fix(swizdb): ensure key dirs get returned in path calls

---

scripts/install/wireguard.sh

`~/.wireguard` owned by root after install for all user
N/A
- `chown` in the wireguard script when configs are created
- Bug fix 
- PR link: 
- PR link: 
| Focal 		|			|			| yup			|				|

fix(wireguard): ensure users can read their own configs

---

scripts/install/bazarr.sh

Primarily fixes the path to the sonarr configuration to make the bazarr installation work as seamlessly as it did previously.
- When installing bazarr after installing sonarrv3, the configuration was not picked up and grep errors was output into console
- Fixes path to sonarr configuration 
- Checks if the configuration is there before trying to `grep`, 
- if file is not there, we show a warning explaining that the config was not found and that the user is on their own in configuring bazarr.
- Does the same check for radarr files
- Bug fix 
| Focal 		|	✅		|			|			|				|
| Raspbian  	|	⚫️ …

[bazarr] Fix configuration failing for sonarrv3

---

.github/workflows/label-conflicts.yml

**HOTFIX** (this branch needs to be merged into develop too)
CI for labeling conflicts does not run when something is pushed to develop
- run ci on develop too
- Bug fix 
- PR link: 
- PR link: 
n/a

ci: check conflicts for develop too

---

scripts/upgrade/calibre.sh
scripts/upgrade/nginx.sh
sources/functions/apt

A quick way to upgrade only a specific package and its dependencies without running a "blind" `apt_install pkg`, and without running an entie system upgrade.
Therefore, `apt_install --only-upgrade sonarr` will upgrade **only** sonarr on the condition it has been previously installed, and will not upgrade any other packages.
Allow for `apt_install --only-upgrade pkg`
- New feature 
- PR link: 
- PR link: 
| Focal 		|			|			|			|	Yup			|

feat: equivalent of `apt-get install --only-upgrade`

---

.github/ISSUE_TEMPLATE/BUG_REPORT.yml
scripts/box
setup.sh
sources/functions/deluge
sources/functions/mono

Adds bullseye support
Updates mono installed version to 6.8 to match focal/bullseye
Reduces packages installed with python deps in deluge install
- bullseye doesn't work
- make bullseye work
- Bug fix 
- New feature 
Deluge & qbit compile
panel/nginx works
all available rtorrent versions work
php untested (assume it will work as everything installs like focal)

feat: add bullseye support

---

scripts/install/rutorrent.sh
scripts/nginx/autodl.sh

- Issue https://github.com/swizzin/swizzin/issues/751
Change from port to gui-server-port to prevent junk ending up in config.
Change from password to gui-server-password to prevent junk in config.
- Bug fix 
- PR link: 
- PR link: 
| Bullseye          |	✅		|			|			|				|

hotfix(autodl): use gui-server-port and gui-server-password

---

scripts/install/sonarr.sh
scripts/nginx/sonarr.sh
scripts/remove/sonarr.sh
scripts/update/sonarr.sh

Moves sonarr to utilizing the tar ball installation as bullseye does not have a repo to install from, yet it shouldn't matter
- Bullseye cannot install Sonarr
- Bug fix 
- PR link: 
- PR link: 
amd64 on buster:
- Fresh install
- Update install (apt to tarball) -- data is moved to .config/Sonarr to allow purging sonarr to remove it from `dpkg -l`
- Removal
amd64 on bullseye:
- Fresh install
- Remove
- Test ARM
- None

update(sonarr): use tar ball for installation to prevent unsupported repo issues

---

.gitignore
scripts/box

Users on `develop` should be able to stay there over `box update` runs and not be forced to master. Furthermore, in order for this branch to give us some real beenfit, might as well run tests on these setups by default.
- More feedback from non-standard users
- Automtaic tests when on "dev" setup
All previous "not updating" scenarios will now additionally run tests on **all** box functions (help, list and invalid args excluded)
- New feature 
- PR link: https://github.com/liaralabs/docs.swizzin.ltd/pull/93
- PR link: 
| …

feat(box): stay on develop over `box update` runs, allow auto-testing

---

scripts/box

- Issue #nr...
- Bug fix 
- New feature 
- PR link: 
- PR link: 

fix: always have .config made by default during user setup

---

sources/functions/qbittorrent

Pre-allocation wasn't enabled by default, so let's enable it for new installations.
Since settings are personal, do not update current users.
- lots of extents per file if using XFS storage
- Enable pre-allocation by default to help prevent fragmentation if using XFS
- Bug fix

fix(qbit): enable preallocation by default

---

scripts/upgrade/calibre.sh

Fixes `os_arch` command not found when upgrading calibre
- Issue #765

fix(calibre): os_arch command not found on upgrade

---

scripts/remove/nextcloud.sh

- `mariadb-server` stays installed and enabled after a nextcloud removal which could be undesired
- Ask user whether or not to remove `mariadb-server` during nextcloud removal
- By default, just drop the database tables and user as before
- Notes: 
- Notes: 
- Notes: using `apt`
- PR link: 
- PR link: 
OS & Version:

feat(nextcloud): Offer to remove database server while removing

---

scripts/install/nextcloud.sh

- Issue #nr...
- Bug fix 
- New feature 
- PR link: 
- PR link: 

fix(nextcloud): broken download links for older versions

---

scripts/nginx/qbittorrent.sh
scripts/update/qbittorrent.sh

- Issue https://github.com/swizzin/swizzin/issues/800
- Apply proxy_cookie_path to qBittorrent nginx config.
- Bug fix 
- PR link: 
- PR link: 
Install two instances of qBittorrent. Try logging in on both and see if one disconnects or "fails to connect"

Fix: write qBittorrent cookie to correct path

---

sources/bencode-libtorrent.patch
sources/functions/rtorrent

This patch backports fixes for multiple denial of service vulnerabilities in rTorrent 0.9.6
- rTorrent 0.9.6 crashes
A patch is applied to libtorrent 0.13.6 which contains the following changes from https://github.com/rakshasa/libtorrent/pull/99:
- Fixes to build_bencode callers, READ_ENC_IA, and object_read_bencode_c
- Bug fix
| Focal 		|	✅		|			|			|				|
I've only performed limited testing of the patch, but these changes have been included in rTorrent since 0.9.7 so they should be safe to merge. I've confirmed that the public proof of concept …

fix(rtorrent): backport bencode fixes to 0.9.6

---

scripts/install/autodl.sh
scripts/install/nginx.sh
scripts/nginx/autodl.sh
scripts/nginx/rutorrent.sh
scripts/rtx
scripts/update/nginx.sh
scripts/upgrade/nginx.sh

Our ruTorrent "quick fix" had reverberating implications on being able to install plugins from head. Basically you can't and installing little things like throttle after the fact is essentially impossible without massive work arounds. This is all due to autodl ruTorrent plugin being out of date.
Since we don't support ruTorrent upgrades, the only official way to "fix" this on a current installation is
```
box remove rutorrent
box install rutorrent
```
- #811 
- autodl-irssi plugin upstream has been pulled into the swizzin org with fixes applied for ruTorrent 4.0
- Unpin ruTorrent version
- Deprecate broken plugins
- Fix filemanager plugins to use new version since the are broken/deprecated
- Fix nginx fancyindex to allow php with split paths
- Bug fix 
- PR link: 
Only tested under …

fix(autodl/rutorrent): update ruTorrent and pull autodl upstream into swizzin org w/ fixes

---

scripts/install/qbittorrent.sh
scripts/remove/qbittorrent.sh
scripts/upgrade/qbittorrent.sh
sources/functions/qbittorrent
sources/functions/utils

Add support for qBittorrent 4.4.*
Prep for future with cmake build pipeline and libtorrent 2.0 support
Don't touch old builds because they work perfectly fine and no sense in creating a bunch of work for a problem that doesn't exist.
- qBittorrent 4.4.0 cannot be installed
- Support cmake build pipeline and qt6.0 with userdocs cmake/qt swizzin crossbuilds
- Build libtorrent 2.0/qbittorrent4.4.* with cmake
- Fix a few packaging thingers
- Bug fix 
- New feature 
- PR link: 
- PR link: 
Only qBittorrent 4.4 should be using the new build method, everything else should be using the older boost/autotools toolchain. Thus you should see no regressions when building 4.1->4.3
4.4 should be supported everywhere 4.3 was (i.e. everywhere but stretch)

feat(qbittorrent): Add support for 4.4 (cmake build/qt6/libtorrent 2.0)

---

scripts/update/10-dependencies.sh
sources/functions/apt

Rather than claiming that apt is constantly installing packages, take the deps list and check if anything is missing from it. If yes, then install those packages; otherwise stay quiet and do nothing.
Tested, does what it says on the box.

fix(apt_install): skip installed packages

---

scripts/install/mango.sh
scripts/nginx/mango.sh
scripts/upgrade/mango.sh
sources/functions/mango

This commit updates Mango config to fix the following errors and warnings:
**New entry:** `plugin_path: $mangodir/plugins`
**Fixes:** `[ERROR] Unable to create directory: '/opt/mango/mango': File exists`
**New entry:** `library_cache_path: $mangodir/.config/mango/library.yml.gz`
**Fixes:**
```
Unhandled exception in spawn: Error opening file with mode 'w': '/opt/mango/mango/library.yml.gz': Not a directory (File::Error)
from usr/share/crystal/src/crystal/system/unix/file.cr:11:7 in 'open'
from usr/share/crystal/src/file.cr:112:5 in '->'
from usr/share/crystal/src/primitives.cr:255:3 in 'run'
from ???
```
**Update entry:** `mangadex.api_url: https://api.mangadex.org/v2`
**Fixes:** `WARN - It looks like you are using the deprecated MangaDex API v1 in your config file.`
- Un-tracked issue
- …

fix(mango): update config to match upstream version

---

sources/functions/rtorrent
sources/xmlrpc-fix.patch

Fixes #824 
The patched file hasn't changed in many moons, so we are good to just apply this across the board.

fix(rtorrent): add patch to prevent ruTorrent xmlrpc crashes

---

sources/functions/mango

Just in time for #827 merge Mango released [v0.25.0](https://github.com/hkalexling/Mango/releases/tag/v0.25.0) today with breaking changes. They removed direct support for Mangadex API and config setting `mangadex.download_queue_db_path` renamed to `queue_db_path` and moved to the root level.
The upstream changes are causing this error on Mango upgrade from Swizzin:
```
Unhandled exception: Unable to create directory: '/opt/mango/mango': File exists (File::AlreadyExistsEr>
from usr/share/crystal/src/crystal/system/unix/dir.cr:65:13 in 'mkdir_p'
from __w/Mango/Mango/src/queue.cr:120:7 in 'default'
from __w/Mango/Mango/src/mango.cr:47:1 in '->'
from usr/share/crystal/src/primitives.cr:255:3 in 'start_parse'
from __w/Mango/Mango/src/mango.cr:137:1 in '__crystal_main'
from …
```

fix(mango): update config to mitigate upstream breaking changes

---

scripts/rtx
sources/functions/rutorrent

Filemanager is breaking ruTorrent.
Stop breaking ruTorrent by reverting commit of filemanager.
Issue filed upstream

fix(rutorrent): pin filemanager to last known working commit

---

sources/functions/apt

finally nailed down a fix for the elusive "package is in depends but not getting installed" bug.
Sometimes grep of our status returns a result of "not-installed" instead of an error. The grep code would match this output and think that the package was installed. Change grep code to `^installed` to ensure we don't match `not-installed`

fix(apt_install): grep mistakes not-installed as ok

---

scripts/install/sabnzbd.sh
scripts/upgrade/sabnzbd.sh

- Set min python version to 3.7.0, 3.6 was dropped by sab upstream. 
- Set pyenv version to 3.10.2 (shipping with windows/macOS builds)
- Use the new `github_latest_version` function to replace grabbing version from GH
- Bug fix 
- PR link: 
- PR link: 
| Focal 		|			|			|		✅	|				|

hotfix(sabnzbd): bump pyenv version

---

scripts/install/panel.sh
scripts/upgrade/panel.sh

Should fix https://github.com/swizzin/swizzin/issues/840
New dependency of authlib fails to download because pip/wheel are out of date and we have installed the deps to build the package ourselves.
Bypass build by making sure we can download the wheel.

fix(panel): keep pip up to date in the venv

---

sources/functions/rtorrent

1. Forces xmlrpc-c to use curl transport to reduce overhead and increase disk i/o throughput.
2. Builds rtorrent and libtorrent (rakshasa) with level 2 optimizations for a stable performance increase on all platforms.
3. Builds xmlrpc-c, rtorrent and libtorrent (rakshasa) with Link Time Compile optimizations. The advantage of these is smaller binaries and better performance. The disadvantage is less debugging information and slightly longer compile times. 
- Bug fix 
- New feature 
- PR link: 
- PR link: 
Build tested on Ubuntu 20.04.4 LTS HWE. 
- Special Note: `-flto` is compatible with xmlrpc-c, rtorrent and libtorrent with no changes required.
| …

Feature: Improve rTorrent performance

---

scripts/install/jellyfin.sh
scripts/update/jellyfin.sh

Fix:
```
E: Malformed entry 1 in list file /etc/apt/sources.list.d/jellyfin.list (URI parse)
E: The list of sources could not be read.
ERROR   Apt failed.
```
Can't fix the install missing deps though :disappointed:

fix(jellyfin): bad deb syntax

---

scripts/update/panel.sh
scripts/upgrade/panel.sh

- Discord report
```
INFO    Currently on branch: develop
...     Updating swizzin local repository
✔   Local repository updated using: develop
INFO    HEAD is now set to 7629805
...     Setting correct permissions on swizzin files
✔   Permissions set
...     Updating panel to latest version
...     Pulling new commits
WARN    Working around unclean git repo
cp: cannot stat 'core/custom': No such file or directory
✔   Commits pulled
...     Checking pip for new depends
✔   Depends up-to-date
...     Restarting Panel
✔   Done!
✔   Done
error: cannot open .git/FETCH_HEAD: Permission denied
```

fix(panel): botched permissions and hardcode reset paths

---

scripts/install/x2go.sh

Fixes Debian quirk
Weird logging about dirmngr not existing or being able to do stuff to a directory. dirmngr is obviously installed...
Create root dir it complains about not existing and problem goes away.
- Discord reports:
The x2go script seems to just refuse to import the key
Manually running the import command; 
```
gpg --no-default-keyring --keyring /usr/share/keyrings/x2go-archive-keyring.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys E1F958385BFE2B6E >> ${log} 2>&1
```
As root resolves all of it
The last one I did just now did not have the key in place

fix(x2go): debian keychain quirk

---

scripts/rtx

DarkBetter & MaterialDesign are supported by ruTorrent now as recurse submodules!
- Bug fix 
- PR link: 
- PR link: 
| Jammy 		|	✅		|			|			|				|

update(rtx): DarkBetter and MaterialDesign as ruTorrent submodules

---

scripts/nginx/autodl.sh
sources/functions/mono
sources/functions/pyenv

Fixes a few instances where swizzin.log would get clobbered due to the use of a single '>' operator.
The following instances were identified:
```
$ grep -E '[^>]>[^>]\s?('\''|")?(\$log|\${log})' -Rn .
./scripts/nginx/autodl.sh:15:        git clone https://github.com/swizzin/autodl-rutorrent.git autodl-irssi > ${log} 2>&1 || { echo_error "git of autodl plugin to main plugins seems to have failed"; }
./sources/functions/mono:9:                gpg --no-default-keyring --keyring /usr/share/keyrings/mono-archive-keyring.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF > ${log} 2>&1
./sources/functions/pyenv:36:    versions=$(/opt/pyenv/bin/pyenv versions 2> "$log")
```
- Un-tracked issue
- Add an extra '>'
- Bug fix
|   			| `amd64` 	| `armhf` …

fix: prevent log clobbering

---

sources/functions/rtorrent

Adds user-supplied patch file support for libtorrent-rakshasa and rtorrent, in the same fashion as is currently implemented for libtorrent-rasterbar. This makes it easier for users to apply their own bugfix patches to work around the slow pace of rtorrent releases.
Patch files are expected in /root with the following example file names:
```
/root/libtorrent-rakshasa-0.13.8.patch
/root/rtorrent-0.9.8.patch
```
- Add user-supplied patch file support for libtorrent-rakshasa and rtorrent
- New feature 
- I'll submit a docs PR if this gets merged
| Jammy 		|		✅	|			|			|				|
| Bullseye		|			|			|			| …

feat(rtorrent): add user patch file support

---

scripts/install/jellyfin.sh

```
sed: can't read /etc/jellyfin/network.xml: No such file or directory
sed: can't read /etc/jellyfin/network.xml: No such file or directory
```

fix(jellyfin): network.xml creation requires several restarts

---

sources/functions/qbittorrent

Following qbit's lead, RC_1_2 is now the default branch for 4.4.x
installer will use branch 2.0 with the `LIBTORRENT_VERSION` env variable, if for some deranged reason you still want to use this branch
```
export LIBTORRENT_VERSION=RC_2_0
box install qbittorrent
```
Also accepts RC_1_2 as a variable, though this is now the default.

qbittorrent: add env variable to support choosing branch in 4.4.x

---

scripts/remove/netdata.sh

Fixes #906 
Uninstall netdata as per docs:
https://learn.netdata.cloud/docs/agent/packaging/installer/uninstall
I guess they no longer ship a uninstaller with the installer :woman_facepalming:

netdata: fix uninstaller

---

scripts/install/mango.sh

Fixes #895
Uses the new github release version function as this is the "new" method for grabbing release URLs.
Added support for arm binaries since they exist now
Tested and working on Bullseye

mango: fix dl links and add arm support

---

scripts/rtx
sources/functions/rutorrent

Fixes:
- not sorting releases properly during ruTorrent install, grabbing beta.2.1 when beta3 exists
- don't pin filemanager anymore unless you're on v4.0-beta.1
- proper string grabbing for beta.2.1 release in the rtx script

fix(rutorrent): plugin related issues and tag matching

---

sources/functions/deluge

The mode on `/etc/swizzin/scripts/deluge.UpdateTracker.py` gets set to 644 during each deluge installation which results in git's working tree being left in a modified state. As far as I can tell this is unnecessary as chmod is always called on the destination file after it's copied, I may have missed something however. It's a slight pain to need to discard the change each time.
```
$ git status -s
M scripts/deluge.UpdateTracker.py
?? scripts/scripts
$ git diff
diff --git a/scripts/deluge.UpdateTracker.py b/scripts/deluge.UpdateTracker.py
old mode 100755
new mode 100644
```
```
$ grep "deluge.UpdateTracker.py" -Rn . -C 1
./sources/functions/deluge-241-    dpkg -i /root/dist/deluge-common_${VERSION}.deb >> "${log}" 2>&1
./sources/functions/deluge:242:    chmod 644 …
```

fix(deluge): don't chmod deluge.UpdateTracker.py in working tree

---

scripts/install/qbittorrent.sh
scripts/upgrade/qbittorrent.sh
sources/functions/deluge
sources/functions/libtorrent
sources/functions/qbittorrent

Closes discord reports of libtorrent failing to compile due to UTP failure (bad commit from upstream) by turning lt branch into tagged release. 
Closes discord reports of deluge failing to build master (due to master being swapped to 2.1)
- Discord report from WalkerServers (LT 1.2 build failures)
- Discord report from @stickz (Deluge 2.1 build failures)
- Add logic from userdocs script to determine a pinned version of libtorrent relative to branch. (fixes https://github.com/arvidn/libtorrent/issues/7158 by tracking versions instead of branch) - achieved in sources/functions/libtorrent functions.
- Add support for Deluge 2.1 - edits to the deluge function file
- Allow users to `export LIBTORRENT_VERSION` for custom versions of libtorrent to be used with deluge - edits to the deluge …

fix: libtorrent versioning & deluge 2.1 support

---

scripts/install/wireguard.sh

As per #925 some issues were discovered with the install method.
Cleaned up buster and removed old/unneeded code

wireguard: fix buster installs, deprecate old platforms (Fixes #925)

---

sources/functions/rtorrent

These changes should accelerate build times to the point where repo installation is no longer required.
- Only compile with link time optimizations if the processor has at least 4 threads.
- Compile with the number of threads available for link time optimizations.

Link time optimization improvements

---

scripts/install/rtorrent.sh
scripts/upgrade/rtorrent.sh
sources/functions/rtorrent

Compile libtorrent and rtorrent with level 1 optimizations if there are 2 or less processor threads available.
- This drastically reduces build times on systems such as virtual machines. It is still better than level 0 repo.
Compile xmlrpc, libtorrent and rtorrent with piping if at least 512 MB of memory is available.
- This greatly reduces build times by using memory instead of temporary files for compilation.
Compile xmlrpc, libtorrent and rtorrent without warning messages.
- Warning messages do not impact functionality of the software. 
- Disabling these reduces compile times by eliminating overhead.
Retrieve libtorrent and rtorrent faster using curl instead of wget.
- This is already installed because it's required for rtorrent.
Don't verbose messages about libtorrent and rtorrent …

rTorrent: Installation speed improvements

---

sources/functions/rutorrent

**Version 4.0.2**
- Adds missing `$cachedPluginLoading` variable.
- Updates default user agent for Chrome.
**Version 4.0.3**
- Adds missing `$pluginJSCacheExpire` variable.
- Adds missing `$miscCacheExpire` variable.

ruTorrent: Version 4.0.2 & 4.0.3 compatibility

---

sources/functions/rtorrent
sources/patches/rtorrent/lockfile-fix.patch

Backports fix for lock file crash merged into rTorrent master. https://github.com/rakshasa/rtorrent/pull/1169

rTorrent: Resolve lockfile crash

---

sources/functions/rtorrent
sources/patches/rtorrent/throttle-fix-0.13.6.patch
sources/patches/rtorrent/throttle-fix-0.13.7-8.patch

Adds support for 10 gigabit throttling when libtorrent is compiled from source. Backports pull request merged into master.  https://github.com/rakshasa/libtorrent/pull/239

rTorrent: Support 10gbit throttle

---

sources/functions/rtorrent

This pull request adds an install advisory for rTorrent and moves the repo release to the bottom of the list.

rTorrent: Add install advisory & sink repo release

---

scripts/install/rtorrent.sh

This PR addresses the notorious issue with piece preloading, where i/o trashing occurs. Many pieces distributing at very low rates speed are attempted to be loaded into memory. We should limit this feature (which is disabled by default) to torrents distributing at a rate of speed faster than 50KB/s to mitigate the problem. If the user enables the feature it will work significantly better.
https://github.com/rakshasa/rtorrent/issues/443

rTorrent: Limit piece preloading to 50KB/s plus

---

scripts/install/autodl.sh

We should use consistent install and upgrade methods for autodl. This implementation is cleaner than the previous one and prevents possible errors from occurring. https://github.com/swizzin/swizzin/blob/master/scripts/upgrade/autodl.sh#L8-L11

AutoDL: Use consistent install/upgrade methods

---

sources/functions/rutorrent

It was introduced and set to false when testing ruTorrent version 4.0.1. The regressions were since resolved in ruTorrent version 4.0.2. See change-log here: https://github.com/Novik/ruTorrent/releases/tag/v4.0.2
The feature purpose is to improve loading times when ruTorrent is hosted on the SAME machine as rTorrent. It performs plugin dependency checks through shell and caches the results. This is a more viable option than executing XMLRPC commands, which is designed be performed for remote hosts. XMLRPC is bound by various bottlenecks such as disk i/o resources.

ruTorrent: Set $localHostedMode to true

---

sources/functions/rtorrent
sources/patches/rtorrent/libtorrent-scanf-0.13.8.patch
sources/patches/rtorrent/libtorrent-udns-0.13.8.patch
sources/patches/rtorrent/rtorrent-scrape-0.9.8.patch

This commit adds an option to install a stability patch for UDP trackers on rTorrent. It's back ported against version 0.9.8.
With this patch, the user will be able to distribute thousands of torrents with UDP trackers, without running into software stability issues. That being said, there are still two unsolved race conditions. This patch is not at fault for causing the crashes.
Install advisory is updated to inform users about the option. libudns is built from source for compatibility with Debian. It takes a few seconds and is only built if the option is enabled.
Changes are tested on Ubuntu 22.04LTS with ARM64. They are confirmed to be working correctly by testing and build logs.

rTorrent: Add UDNS install option

---

scripts/install/rutorrent.sh
sources/functions/ffmpeg

ffmpeg is required for the screenshots plugin. Many users want to use this plugin, so it's not a good idea to gut the functionality. It's supported on all platforms and is a tiny binary file.
This commit makes the ffmpeg install script modular, so it's easier to maintain and changes apply to ruTorrent. It only installs ffmpeg if it's not already installed.
These changes are tested on Ubuntu 22.04 LTS ARM64. They are confirmed to be working and the screenshots plugin is now functional out of the box. When users deploy ruTorrent, everything will work as intended!

ruTorrent: Install ffmpeg by default

---

sources/functions/rutorrent

Updates configuration variables for version 4.1.4. Cached age expiry is removed due to bugs with dynamic hooks. These variables serve no purpose anymore, other than to confuse the user. https://github.com/Novik/ruTorrent/releases/tag/v4.1.4

ruTorrent: update config for v4.1.4

---

scripts/install/rtorrent.sh
scripts/upgrade/curl.sh
scripts/upgrade/rtorrent.sh
sources/functions/curl

This pull request enhances curl for rTorrent by recompiling it with c-ares support for threaded DNS lookups. The latest stable release of curl from Debian Bullseye back-ports is used. The latest upstream release of c-ares is used.
Tested on Ubuntu 22.04LTS ARM64 and confirmed to be working.

rTorrent: Compile curl with c-ares

---

sources/functions/rutorrent

This commit drops rar archive creation on ARM64 because it's not supported. It only makes the adjustment to ARM to keep the x86 platform fully functional. This small change makes the file manager plugin work properly, without errors.
Changes tested on Ubuntu 22.04 LTS ARM64 and confirmed to be working. This makes ruTorrent function out of the box on ARM.

ruTorrent: ARM64 support for file manager

---

sources/functions/curl

**Tested on Ubuntu 22.04 LTS ARM64**.
- Decreased build time from 3 minutes to 60 seconds on ARM64.
- Always enable Link Time Optimizations.
- Use Level 3 compiler optimizations with native march.

cURL: Optimized cmake building

---

sources/functions/curl

This commit fixes a bug where `curl` cannot be upgraded if the `curl` binary is not functioning. It uses `git` instead of `curl` to retrieve the latest version of `c-ares` from GitHub. This allows `box upgrade curl` to always work regardless of distribution upgrades. It produces the same output as `github_latest_version c-ares/c-ares`.

cURL: Upgrade without cURL binary

---

sources/patches/rtorrent/libtorrent-udns-0.13.8.patch

Author pinged here about fix for UDNS failing for IPV6. rTorrent doesn't offer meaning IPV6 support, so we should only attempt to resolve UDP trackers using IPV4 to prevent failures. https://github.com/rakshasa/libtorrent/pull/134#issuecomment-1593671383
See commit https://github.com/rakshasa/libtorrent/commit/25100693ee7ace605fbdbf58339b55af0d59b9f2 for more details.

rTorrent: Fix bug with UDNS branch

---

scripts/update/10-dependencies.sh
sources/functions/gcc

This commit sets GCC 12 as the Ubuntu 22.04 LTS system default. It allows users to unlock the latest improvements for compiled software solutions. It is capable of repairing linkage from previous distribution releases or manual user adjustments.
Implemented as suggested in #992. The plan is to only support Jammy for simplicity. It is pointless upgrading Focal because it's already two versions behind. The user should upgrade their distribution release, if they want the latest software packages.
Tested on Ubuntu 22.04 LTS ARM64. The script was successful.

Jammy: GCC 12 system default

---

sources/functions/curl

This is required to fix linking to zlib on some systems. closes #1037.

rTorrent: Build shared libs for curl

---

scripts/install/rtorrent.sh

This commit fixes an I/O thrashing issue with mechanical hard drives. We need to save session files for torrents hourly instead of once every 20 minutes by default. Otherwise, it will trash the disk, if the user has thousands of torrents. This operation can take minutes, especially with shared resources. rTorrent saves torrent information into session files on disk. This is very intensive.
See here for the default value of 20 minutes which is 1200 seconds. Adding the `session_save` function to `rtorrent.rc` overrides this value. https://github.com/rakshasa/rtorrent/blob/master/src/main.cc#LL358C63-L358C63

rTorrent: Save session files hourly

---

.github/ISSUE_TEMPLATE/config.yml

Remove feathub from GH Issue tempalte
- First reported on the [Discord](https://discord.com/channels/577667871727943696/577667871727943700/1070733509301379072)
- Removed from README in https://github.com/swizzin/swizzin/commit/9743e49175209bc59ec636b302519ea78df60e8a
- Bug fix

remove feathub link from issue template

---

scripts/nginx/lidarr.sh
scripts/nginx/radarr.sh
scripts/nginx/readarr.sh
scripts/nginx/sonarr.sh
scripts/update/lidarr.sh
scripts/update/radarr.sh
scripts/update/readarr.sh
scripts/update/sonarr.sh

Allow access to `/feed/calendar` since GCal import doesn't like inline HTTP auth
- Bypass authentication for path `/feed/calendar` for *arrs
- sonarr
- lidarr
- radarr
- readarr
- New feature 
Since it targets nginx config, `nginx -t` was used instead and formatting was copied from previous instances of API exclusion

allow access to /feed/calendar via NGINX

---

scripts/remove/nginx.sh

`php-mcrypt` and `php-geoip` are not supported on some operating systems. We need to check before attempting to remove them. Don't specify packages for removal more than once. If we miss anything, we can purge it. This is bad for maintenance.

Nginx: Fix package errors during remove

---

scripts/install/pyload.sh

Fixes installing PyLoad
Running Ubuntu 22.04 LTS, and for whatever reason Pyload kept erroring during the DB setup.
Checked the script, and tried running the erroring command myself and kept getting the following error 
`ImportError: pycurl: libcurl link-time ssl backend (openssl) is different from compile-time ssl backend (none/other)`
Added a work around to fix the issue and tested it successfully. 
- Bug fix

Fix pyload.sh

---

scripts/install/nginx.sh

This commit starts a background task for `openssl dhparam -out dhparam.pem` to allow package installation at the same time. This reduces installation time of `nginx` by 30s on x86 and 60s on ARM64 without any real disadvantages. `temp.log` is created to prevent a race condition with logging. The logging output is appended to `swizzin.log` afterwards and `temp.log` is removed.
Tested on Ubuntu 22.04 LTS ARM64. Works as expected. Package installation finished before `openssl dhparam -out dhparam.pem`. The bash script waited for the background task to finish before proceeding. 60s of installation time was saved.

Nginx: dhparm background task

---

sources/functions/curl
sources/functions/rtorrent
sources/patches/rtorrent/libtorrent-udns-0.13.8.patch
unattended.example.env

* Improve compile level optimizations for rtorrent. Utilize level 3 optimizations with 8+ threads. Apply optimizations to libudns. Decrease thread count from 2 to 1 for level 1 optimizations. Level 2 is still relatively quick on 2 threads.
* Fix support for unattended setup by refactoring version checking code. Add example for 0.9.8 source unattended.
* Fix a UDNS patch error regression from a previous commit. Remove IPV6 UDNS queries a different way instead.
* Fix a couple issues with curl. Silence build noise if la file doesn't exist. Fix curl not working properly by running ldconfig on the library before the binary.
Tested on Ubuntu 22.04 LTS ARM64 without unattended setup. Recommended to test with unattended before merging. 
closes #966.

rTorrent: Fix a bunch of things

---

scripts/install/tautulli.sh
scripts/remove/tautulli.sh
scripts/update/tautulli.sh

Tautulli requires 3.8 now, so swap installer to use this by minimum and forcefully update all users to a venv. Additionally update users who don't have 3.8 minimum and push them onto pyenv.

tautulli: use venv and pyenv on py3<3.7

---

sources/functions/rtorrent

Resolves: `svn: E155000: '/tmp/xmlrpc-c' is already a working copy for a different URL`
I came across this error when testing the develop branch. The first instance of `svn co` failed, which caused the second one to fail. The simplest solution is bump xmlrpc-c to super-stable and update the link to the svn handle.

rTorrent: Bump xmlrpc-c to super stable

---

scripts/nginx/qbittorrent.sh
scripts/update/qbittorrent.sh

Bad security default of leaving qbit bound to `*` by default with nginx installed.
Update default, warn existing users. The warning may be tiresome to endure but I don't believe we should alter the value forcibly as the hook would end up running every time someone updates and would be annoying to fight if they want the port open on purpose.
Could use swizzdb to refine this further and only make the check one time but would require additional effort

qbittorrent: update default bind with nginx, warn existing users

---

sources/functions/curl

Resolves a bug with curl when installation is terminated midway and restarted. Script will freeze by prompting for override.

curl: Override to silence unzip replace prompt

---

sources/functions/rtorrent

Adds PGO build branch to rTorrent that incorporates UDNS. Tested on Ubuntu 22.04LTS. Confirmed to be working.

rtorrent: Add PGO build option

---

scripts/nginx/qbittorrent.sh
scripts/update/qbittorrent.sh

The warning about the qbittorrent webinterface appears even for correctly set 127.0.0.1, because * is not escaped in the grep.
- Un-tracked
- replace * with \* in the webinterface grep
- PR link: 
- PR link: 
Tested the grep command with and without escape \ in the terminal.

qbittorrent: Fix interface grep 

---

scripts/nginx/calibreweb.sh
scripts/update/calibreweb.sh

Setting `proxy_bind` to `$server_addr` can cause issues if the connecting client is attempting to connect to a different IP protocol address than the backend supports (IPv6 vs IPv4)
This removes explicitly setting the `proxy_bind` setting, and instead relies on the default nginx behaviour (of binding to the same protocol as the upstream service)
`calibreweb` currently doesn't work with IPv6 as internally, CalibreWeb binds to an IPv4 address `127.0.0.1` - and if you attempt to hit Nginx with a client using IPv6 - `$server_addr` will be an IPv6 address - preventing it to talk to the upstream IPv4 address
- Issue #1071 1071
- Changing `/scripts/nginx/calibreweb.sh` to remove setting `proxy_bind`, and instead rely on default behaviour.
- [✅] Branch was made off the …

Don't set `proxy_bind` and instead rely on default behaviour.

---

sources/functions/rtorrent
sources/patches/rtorrent/fast-session-loading-0.9.8.patch
sources/patches/rtorrent/lookup-cache-0.13.8.patch
sources/patches/rtorrent/piece-boundary-fix-0.13.8.patch
sources/patches/rtorrent/rtorrent-ml-fixes-0.9.8.patch
sources/patches/rtorrent/scgi-fix.patch
sources/patches/rtorrent/session-file-fix.patch
sources/patches/rtorrent/xmlrpc-logic-fix.patch

- Resolves an annoying bug with rtorrent where torrent progress is reported as 200%.
- Fixes a problem where xmlrpc-c information fails to update if user is running too many torrents.
- Resolves a data corruption issue with torrent session files during a power loss.
- Resolves a rtorrent crash causing by sending invalid xmlrpc logic to the torrent client.
- Resolves three instances of memory leaks with the rtorrent software.

rTorrent: Add latest development fixes

---

sources/functions/autobrr

Fix for autobrr installer/upgrader that broke when we started to ship multiple types of packages per arch.
- Un-tracked issue reported on Discord
-  Does an additional grep for `.tar.gz` to get the correct archive.
- Bug fix 
- PR link: 
- PR link: 
- Install autobrr
- Upgrade autobrr

fix(autobrr): install/updater select correct package

---

sources/functions/navidrome

The latest releases of Navidrome for amd64 arch no longer includes `x86_64` in the URL, this has been replaced with `amd64` - therefore downloads/installs currently fail.
- #1100 
- Replace `x86_64` with `amd64` within `sources/functions/navidrome`
- Add the `-f` flag to the `curl` download line - right now the 'download failed' check isn't being triggered on HTTP 404, instead we're getting a `navidrome.tar.gz` file with the contents of `Not Found`
- PR link: 
- PR link: 
- Fresh Swizzin install
- Attempt to install Navidrome. Fail. :( Check code. :)
- URL changed.
- Update URL
- Attempt to install again!
- It works!
| …

fix: navidrome fails to download on amd64 arch

---

sources/functions/libtorrent

Swapped boost download url because the account on the main site is deactivated, also changed wget to curl to download more than an html file from sourceforge
The boost download redirects to landing.jfrog.com/reactivate-server/boostorg, wget loads a html page and because it downloads something the fallback isn't working, could be fixed, but is a bit more work, so I canged the dl sites for now as a quick fix. Also changed wget to curl because I got problems with wget and loading from sourceforge.
Also: Is there a reason why boost 1.75 is still in use while there was a boost 1.84 release this december? 1.75 was released in december 2020. Didn't change version in case of breaking stuff.
- Changed boost download method in libtorrent function
- …

Changed boost download

---

sources/functions/rtorrent

- Set `mktorrent` compiler to `gcc`. Apply optimization flags.
- Fix `xmlrpc` c flags. Ensure optimization level is applied during the build.
- configure libtorrent with `--enable-aligned` to prevent crashes

rTorrent: Fix build flags

---

sources/functions/curl

Upgrades curl to the latest bookworm backports. Fixes broken version linkage for curl binary. Tested in Debian 12 x86.

Curl: Upgrade to v8.4

---

sources/functions/rtorrent

This commit fixes a critical stability issue with xmlrpc-c on rtorrent. It pins xmlrpc-c to stable revision 3212 (which has been tested) to prevent a future reoccurrence. We were running a rolling release and the author introduced a regression. It was required to hard code 3212 because the variable notation did not work. Tested on Ubuntu 22.04 LTS by two users. Confirmed to be stable.

rTorrent: Pin xmlrpc-c to stable revision 3212

---

sources/functions/fpm

This commit resolves a critical installation issue on Ubuntu 20.04 with rTorrent, Deluge and qBittorrent when building from source. There is a package conflict with `dotenv` that prevents `fpm` from installing.
```
ERROR:  Error installing fpm:
The last version of dotenv (>= 0) to support your Ruby & RubyGems was 2.8.1. Try installing it with `gem install dotenv -v 2.8.1` and then running the current command again
dotenv requires Ruby version >= 3.0. The current ruby version is 2.7.0.0.
```

FPM: Fix Ubuntu 20.04 installation

---

sources/functions/curl

Debian decided to bump the curl version. We need to add a dependency to ensure it compiles.

curl: Add missing libbrotli-dev dependency

---

sources/functions/libtorrent

Old OS's cannot use 1.85 and new OS cannot compile libtorrent 1.2 without a boost upgrade.
Appears to work successfully.
Following cases were tested:
Focal: Deluge 1.3 + Deluge 2.1
Jammy: Deluge 1.3 + Deluge 2.1
Noble: Deluge 2.1 (Bookworm reports in issues)

libtorrent: upgrade boost to 1.85 for bookworm and newer

---

sources/functions/rutorrent

This 1 line of code (that you don't have to review @liaralabs) will stop ruTorrent v5.0 from exploding (when it's released) for seamless upgrades! `rm -rf /srv/rutorrent/plugins/dump`

ruTorrent v5.0 compatibility

---

sources/functions/rtorrent

Adds support for rTorrent 0.10.0 without dropping old versions and fixes xmlrpc-c not to build unused code. Tested on Ubuntu Server 24.04.1 LTS. Successfully downloaded Linux ISO in 15 seconds with new version of rTorrrent!

rTorrent: Version 0.10.0 & fix xmlrpc-c

---

sources/functions/rtorrent
sources/patches/rtorrent/1310-scgi-fix.patch

- Add support for rTorrent `0.15.1` with vendor `tinyxml2` instead of `xmlrpc-c`. This is now stable and tested with the arr suite and other indexers. It contains a significant reduction in overhead and will reduce future code maintenance. [rakshasa](https://github.com/rakshasa) posted a hotfix, so would could distribute a stable release of `tinyxml2`.
- Patch rTorrent `0.10.0` with a common scgi fix to a software crash. Linux distributions are distributing this patch.
- Remove the broken `PGO` option from the whiptail menu. It never worked properly and this will reduce maintenance.
- Remove note about `UDNS` from the whiptail menu. Add keyword "latest" instead to encourage selection of the most stable release.

rTorrent: Add support for 0.15.1

---

sources/functions/rtorrent
sources/patches/rtorrent/libtorrent-0.15.3-resume-fix.patch

This pull request adds support for rTorrent 0.15.5. There is no patching required because it's stable.
1. rTorrent 0.15.4 will not be supported because it's not stable.
This pull request also patches rTorrent 0.15.3 to resolve two known software crashes.
1. rTorrent 0.15.2 will not be supported because it's not stable.

rTorrent: Add support for v0.15.5
